"""orchestrator memory crew catalog pricing subscription usage

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-08-10 23:29:38.137019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('pricing_json', sa.JSON(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_id')
    )
    op.create_index(op.f('ix_model_catalog_provider'), 'model_catalog', ['provider'], unique=False)
    op.create_table('model_pricing_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('input_per_million', sa.Float(), nullable=True),
    sa.Column('cached_input_per_million', sa.Float(), nullable=True),
    sa.Column('output_per_million', sa.Float(), nullable=True),
    sa.Column('additional_pricing_json', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricing_snapshots_model_id'), 'model_pricing_snapshots', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_pricing_snapshots_provider'), 'model_pricing_snapshots', ['provider'], unique=False)
    op.create_table('crew_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('model_policy', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('uses_default_prompt', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role')
    )
    op.create_index(op.f('ix_crew_configs_user_id'), 'crew_configs', ['user_id'], unique=False)
    op.create_table('crew_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('orchestrator_run_id', sa.String(length=36), nullable=True),
    sa.Column('crew_role', sa.String(length=32), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('requested_model', sa.String(length=120), nullable=True),
    sa.Column('actual_model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_summary', sa.String(length=500), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_runs_orchestrator_run_id'), 'crew_runs', ['orchestrator_run_id'], unique=False)
    op.create_index(op.f('ix_crew_runs_user_id'), 'crew_runs', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'memory_type', 'key')
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.add_column('llm_usage', sa.Column('requested_model', sa.String(length=120), nullable=True))
    op.add_column('llm_usage', sa.Column('crew_role', sa.String(length=32), nullable=True))
    op.add_column('llm_usage', sa.Column('orchestrator_run_id', sa.String(length=64), nullable=True))
    op.add_column('llm_usage', sa.Column('provider_request_id', sa.String(length=120), nullable=True))
    op.add_column('llm_usage', sa.Column('cached_input_tokens', sa.Integer(), nullable=True))
    op.add_column('llm_usage', sa.Column('reasoning_tokens', sa.Integer(), nullable=True))
    op.add_column('llm_usage', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('llm_usage', sa.Column('provider_reported_cost', sa.Float(), nullable=True))
    op.add_column('llm_usage', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('llm_usage', sa.Column('cost_currency', sa.String(length=3), nullable=False,
                                         server_default='USD'))
    op.add_column('llm_usage', sa.Column('cost_source', sa.String(length=20), nullable=False,
                                         server_default='UNKNOWN'))
    op.add_column('llm_usage', sa.Column('pricing_snapshot_id', sa.String(length=36), nullable=True))
    op.add_column('llm_usage', sa.Column('status', sa.String(length=16), nullable=False,
                                         server_default='success'))
    op.add_column('llm_usage', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # SQLite cannot ALTER COLUMN; use batch mode (recreates the table there, no-op cost on PG)
    with op.batch_alter_table('llm_usage') as batch:
        batch.alter_column('input_tokens', existing_type=sa.INTEGER(), nullable=True)
        batch.alter_column('output_tokens', existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f('ix_llm_usage_crew_role'), 'llm_usage', ['crew_role'], unique=False)
    op.create_index(op.f('ix_llm_usage_orchestrator_run_id'), 'llm_usage', ['orchestrator_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_orchestrator_run_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_crew_role'), table_name='llm_usage')
    with op.batch_alter_table('llm_usage') as batch:
        batch.alter_column('output_tokens', existing_type=sa.INTEGER(), nullable=False)
        batch.alter_column('input_tokens', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('llm_usage', 'finished_at')
    op.drop_column('llm_usage', 'status')
    op.drop_column('llm_usage', 'pricing_snapshot_id')
    op.drop_column('llm_usage', 'cost_source')
    op.drop_column('llm_usage', 'cost_currency')
    op.drop_column('llm_usage', 'estimated_cost')
    op.drop_column('llm_usage', 'provider_reported_cost')
    op.drop_column('llm_usage', 'total_tokens')
    op.drop_column('llm_usage', 'reasoning_tokens')
    op.drop_column('llm_usage', 'cached_input_tokens')
    op.drop_column('llm_usage', 'provider_request_id')
    op.drop_column('llm_usage', 'orchestrator_run_id')
    op.drop_column('llm_usage', 'crew_role')
    op.drop_column('llm_usage', 'requested_model')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_crew_runs_user_id'), table_name='crew_runs')
    op.drop_index(op.f('ix_crew_runs_orchestrator_run_id'), table_name='crew_runs')
    op.drop_table('crew_runs')
    op.drop_index(op.f('ix_crew_configs_user_id'), table_name='crew_configs')
    op.drop_table('crew_configs')
    op.drop_index(op.f('ix_model_pricing_snapshots_provider'), table_name='model_pricing_snapshots')
    op.drop_index(op.f('ix_model_pricing_snapshots_model_id'), table_name='model_pricing_snapshots')
    op.drop_table('model_pricing_snapshots')
    op.drop_index(op.f('ix_model_catalog_provider'), table_name='model_catalog')
    op.drop_table('model_catalog')
    # ### end Alembic commands ###
